name: "RIPE Atlas Probe"
version: "5130.2"
slug: ripe_atlas_probe
description: "Run a RIPE Atlas software probe on your Home Assistant system"
url: "https://github.com/prmx/ha-atlas-probe"
image: "ghcr.io/prmx/ha-atlas-probe-{arch}"
arch:
  - aarch64
  - amd64
init: false
startup: system
privileged:
  - NET_ADMIN
  - NET_RAW
host_network: true
map:
  - config:rw
options:
  log_level: info
  telnetd_port: 2023
  http_post_port: 8080
  rxtxrpt: false
schema:
  log_level: list(debug|info|warning|error)
  probe_key: str?
  telnetd_port: port
  http_post_port: port
  rxtxrpt: bool
